config:
  # First, set the default
  default: true

  # Per-rule settings in alphabetical order
  code-block-style:                 # MD046
    style: "fenced"
  # Temporarily disable MD014 until we fix problems
  commands-show-output: false       # MD014
  emphasis-style: false             # MD049
  header-style:                     # MD003
    style: "atx"
  hr-style:                         # MD035
    style: "---"
  line-length:                      # MD013
    code_blocks: false
    tables: false
    headings: true
    heading_line_length: 100
    line_length: 2000
  no-duplicate-heading:             # MD024
    siblings_only: true
  no-emphasis-as-heading: false     # MD036
  no-inline-html: false             # MD033
  no-trailing-punctuation:          # MD026
    punctuation: ".,;:!。，；：！？"
  no-trailing-spaces: false         # MD009
  reference-links-images: false     # MD052
  ul-style:                         # MD004
    style: "dash"

  # Disable this rule in the CLI project, because 1. 1. 1. 1. numbering
  # is rendered verbatim in CLI output
  ol-prefix: false                  # MD029