[package]
name = "besedarium"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "besedarium"
path = "src/lib.rs"

# No [[bin]] section, as we are removing main.rs and do not want an executable artifact

[dependencies]

[dev-dependencies]
trybuild = "1.0.85"
