name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --all --verbose
      - name: Run clippy
        run: cargo clippy --all -- -D warnings
      - name: Run fmt check
        run: cargo fmt --all -- --check
